// mockData.js — static dev data (backend schema adapter lives in App.jsx).
// Schema: { email_id, subject, category_type: COURSE|ANNOUNCEMENT, source, sender,
//           deadline_date: "YYYY-MM-DD HH:mm", action_summary }
// 9 items → 3 pages at 4/page. Dates are set relative to Sep 1, 2026.

export const MOCK_CARDS = [
  {
    email_id: 'mock-1',
    subject: 'MatE 190 Problem Set 4 due',
    category_type: 'COURSE',
    source: 'MatE 190',
    sender: 'Prof. Aquino <aquino@up.edu.ph>',
    deadline_date: '2026-08-31 23:59',
    action_summary: 'Submit problem set',
  },
  {
    email_id: 'mock-2',
    subject: 'MatE 183 Lab Report 3 deadline',
    category_type: 'COURSE',
    source: 'MatE 183',
    sender: 'Dr. Reyes <reyes@up.edu.ph>',
    deadline_date: '2026-09-02 17:00',
    action_summary: 'Submit lab report',
  },
  {
    email_id: 'mock-3',
    subject: 'COE Seminar: AI in Materials Science',
    category_type: 'ANNOUNCEMENT',
    source: 'College of Engineering',
    sender: 'COE Student Council <coe.sc@up.edu.ph>',
    deadline_date: '2026-09-08 13:00',
    action_summary: 'Attend seminar',
  },
  {
    email_id: 'mock-4',
    subject: 'MatE 200 Proposal draft review',
    category_type: 'COURSE',
    source: 'MatE 200',
    sender: 'Dr. Santos <santos@up.edu.ph>',
    deadline_date: '2026-09-10 12:00',
    action_summary: 'Submit proposal draft',
  },
  {
    email_id: 'mock-5',
    subject: 'MatE 190 Quiz 4 announcement',
    category_type: 'COURSE',
    source: 'MatE 190',
    sender: 'Dept of Materials Engineering <mate@up.edu.ph>',
    deadline_date: '2026-09-12 09:00',
    action_summary: 'Prepare for quiz',
  },
  {
    email_id: 'mock-6',
    subject: 'Library Workshop: Citation Tools',
    category_type: 'ANNOUNCEMENT',
    source: 'UP Main Library',
    sender: 'University Library <library@up.edu.ph>',
    deadline_date: '2026-09-15 10:00',
    action_summary: 'RSVP to workshop',
  },
  {
    email_id: 'mock-7',
    subject: 'MatE 183 Homework 6 assigned',
    category_type: 'COURSE',
    source: 'MatE 183',
    sender: 'Prof. Dela Cruz <delacruz@up.edu.ph>',
    deadline_date: '2026-09-18 23:59',
    action_summary: 'Submit homework',
  },
  {
    email_id: 'mock-8',
    subject: 'DOST Scholarship Renewal notice',
    category_type: 'ANNOUNCEMENT',
    source: 'DOST-SEI',
    sender: 'DOST Scholarship Office <dost.sei@dost.gov.ph>',
    deadline_date: '2026-09-22 17:00',
    action_summary: 'Prepare documents',
  },
  {
    email_id: 'mock-9',
    subject: 'MatE 200 Final report outline',
    category_type: 'COURSE',
    source: 'MatE 200',
    sender: 'Dr. Santos <santos@up.edu.ph>',
    deadline_date: '2026-09-25 23:59',
    action_summary: 'Submit outline',
  },
];
