// mockData.js — static dev data (backend schema adapter lives in App.jsx).
// Schema: { email_id, subject, category_type: COURSE|ANNOUNCEMENT, source, sender,
//           deadline_date: "YYYY-MM-DD HH:mm", action_summary }
// 9 items → 3 pages at 4/page. Dates are set relative to Sep 1, 2026.
// All course codes, senders, and domains are FICTIONAL — no real institution.

export const MOCK_CARDS = [
  {
    email_id: 'mock-1',
    subject: 'CS 230 Problem Set 4 due',
    category_type: 'COURSE',
    source: 'CS 230',
    sender: 'Prof. Aquino <aquino@example.edu>',
    deadline_date: '2026-08-31 23:59',
    action_summary: 'Submit problem set',
  },
  {
    email_id: 'mock-2',
    subject: 'EE 130 Lab Report 3 deadline',
    category_type: 'COURSE',
    source: 'EE 130',
    sender: 'Dr. Reyes <reyes@example.edu>',
    deadline_date: '2026-09-02 17:00',
    action_summary: 'Submit lab report',
  },
  {
    email_id: 'mock-3',
    subject: 'Seminar: AI in Engineering',
    category_type: 'ANNOUNCEMENT',
    source: 'College of Engineering',
    sender: 'College Council <coe.sc@example.edu>',
    deadline_date: '2026-09-08 13:00',
    action_summary: 'Attend seminar',
  },
  {
    email_id: 'mock-4',
    subject: 'MATH 150 Proposal draft review',
    category_type: 'COURSE',
    source: 'MATH 150',
    sender: 'Dr. Santos <santos@example.edu>',
    deadline_date: '2026-09-10 12:00',
    action_summary: 'Submit proposal draft',
  },
  {
    email_id: 'mock-5',
    subject: 'CS 230 Quiz 4 announcement',
    category_type: 'COURSE',
    source: 'CS 230',
    sender: 'Dept of Computing <dept@example.edu>',
    deadline_date: '2026-09-12 09:00',
    action_summary: 'Prepare for quiz',
  },
  {
    email_id: 'mock-6',
    subject: 'Library Workshop: Citation Tools',
    category_type: 'ANNOUNCEMENT',
    source: 'University Library',
    sender: 'University Library <library@example.edu>',
    deadline_date: '2026-09-15 10:00',
    action_summary: 'RSVP to workshop',
  },
  {
    email_id: 'mock-7',
    subject: 'ME 210 Homework 6 assigned',
    category_type: 'COURSE',
    source: 'ME 210',
    sender: 'Prof. dela Cruz <delacruz@example.edu>',
    deadline_date: '2026-09-18 23:59',
    action_summary: 'Submit homework',
  },
  {
    email_id: 'mock-8',
    subject: 'Scholarship Renewal notice',
    category_type: 'ANNOUNCEMENT',
    source: 'Scholarship Office',
    sender: 'Scholarship Office <scholarship@example.gov>',
    deadline_date: '2026-09-22 17:00',
    action_summary: 'Prepare documents',
  },
  {
    email_id: 'mock-9',
    subject: 'MATH 150 Final report outline',
    category_type: 'COURSE',
    source: 'MATH 150',
    sender: 'Dr. Santos <santos@example.edu>',
    deadline_date: '2026-09-25 23:59',
    action_summary: 'Submit outline',
  },
];
